import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider,auth } from '@clerk/nextjs'
// import { GoogleOAuthProvider } from '@react-oauth/google';

import SessionWrapper from "@/components/SessionWrapper";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const {user,userId,getToken}= auth();
  return (
    <>

<ClerkProvider>
 <SessionWrapper>
  <html lang="en">
   <body className={inter.className}>
   <Navbar/>
  {children}
   </body> 
{/* <script src="https://apis.google.com/js/platform.js" async defer></script> */}
  </html>
 </SessionWrapper>
</ClerkProvider>

  
    </>
  );
}
