import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
// import { GoogleOAuthProvider } from '@react-oauth/google';
import SessionWrapper from "@/components/SessionWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
<ClerkProvider>
 <SessionWrapper>
  <html lang="en">
   <body className={inter.className}>
  {children}
   </body> 
{/* <script src="https://apis.google.com/js/platform.js" async defer></script> */}
  </html>
 </SessionWrapper>
</ClerkProvider>
  
    </>
  );
}
